"""Characterization tests comparing LangGraph StateGraph execution with Orchestrator.

Validates Tasks P0-02 and P1-01 from docs/migration/backlog.md:
- Verify sequential Orchestrator runs to completion and produces valid response
- Verify LangGraphOrchestrator runs to completion with full parity:
    * Defect D0a resolved (Decimal/float operand in validate_request)
    * Defect D0b resolved (parallel fan-out branches cleanly merge via Annotated reducers)
    * Defect D1 resolved (ApprovalArtifact created using HumanApprovalWorkflowAgent)
    * Defect D2 resolved (persist_workflow_artifacts & audit events saved to WorkflowStore)
    * Trades generated by LangGraph match Orchestrator exactly
"""

import pytest

from app.contracts.common import WorkflowState
from app.contracts.workflow import PortfolioRebalanceRequest
from app.persistence.memory_store import InMemoryWorkflowStore
from app.services.langgraph_graph import LangGraphOrchestrator, build_workflow_graph
from app.services.langgraph_state import create_initial_state
from app.services.orchestrator import Orchestrator
from tests.test_rebalance import request_payload


@pytest.fixture
def rebalance_request() -> PortfolioRebalanceRequest:
    """Construct standard valid rebalance request."""
    return PortfolioRebalanceRequest.model_validate(request_payload())


@pytest.mark.asyncio
async def test_orchestrator_baseline_succeeds(rebalance_request: PortfolioRebalanceRequest) -> None:
    """Verify that sequential Orchestrator runs to completion and produces valid response."""
    store = InMemoryWorkflowStore()
    orchestrator = Orchestrator(store)

    response = await orchestrator.run(rebalance_request)

    assert response.workflow_state == WorkflowState.NORMAL
    assert response.recommendation_package is not None
    assert response.recommendation_package.approval_eligibility is True
    assert response.approval_artifact is not None
    assert response.approval_artifact.approval_status == "PENDING"
    assert response.approval_artifact.recommendation_hash is not None

    # Check store persistence
    stored_portfolio = store.get_portfolio(rebalance_request.account_profile.account_id)
    assert stored_portfolio is not None
    stored_approval = store.get_approval(response.approval_artifact.approval_id)
    assert stored_approval is not None


@pytest.mark.asyncio
async def test_langgraph_parity_with_orchestrator(rebalance_request: PortfolioRebalanceRequest) -> None:
    """
    Verify that LangGraphOrchestrator runs to completion and achieves parity with Orchestrator (Task P1-01).

    Resolves:
    - D0a: Decimal/float operand in validate_request
    - D0b: parallel node state update collision
    - D1: ApprovalArtifact creation using HumanApprovalWorkflowAgent
    - D2: WorkflowStore persistence parity (portfolio, approval, audit events)
    """
    orch_store = InMemoryWorkflowStore()
    orch = Orchestrator(orch_store)
    orch_response = await orch.run(rebalance_request)

    lg_store = InMemoryWorkflowStore()
    lg_orchestrator = LangGraphOrchestrator(lg_store)
    lg_response = await lg_orchestrator.run(rebalance_request)

    # 1. Workflow State Parity
    assert lg_response.workflow_state == orch_response.workflow_state == WorkflowState.NORMAL

    # 2. Recommendation Package Parity
    lg_rec = lg_response.recommendation_package
    orch_rec = orch_response.recommendation_package
    assert lg_rec is not None and orch_rec is not None
    assert lg_rec.approval_eligibility == orch_rec.approval_eligibility is True
    assert lg_rec.current_allocation == orch_rec.current_allocation
    assert lg_rec.target_allocation == orch_rec.target_allocation
    assert lg_rec.proposed_allocation == orch_rec.proposed_allocation
    assert lg_rec.risk_policy.verdict == orch_rec.risk_policy.verdict

    # 3. Trade Proposals Exact Parity (comparing deterministic fields, excluding random trade_id)
    orch_trades = [
        {k: v for k, v in t.model_dump().items() if k != "trade_id"}
        for t in orch_rec.proposal.trades
    ]
    lg_trades = [
        {k: v for k, v in t.model_dump().items() if k != "trade_id"}
        for t in lg_rec.proposal.trades
    ]
    assert len(lg_trades) > 0, "Expected non-empty trades"
    assert lg_trades == orch_trades

    # 4. Approval Artifact Parity
    assert lg_response.approval_artifact is not None
    assert lg_response.approval_artifact.approval_status == "PENDING"
    assert lg_response.approval_artifact.recommendation_hash is not None
    assert len(lg_response.approval_artifact.recommendation_hash) == 64

    # 5. Persistence Parity (Defect D2)
    acct_id = rebalance_request.account_profile.account_id
    stored_portfolio = lg_store.get_portfolio(acct_id)
    assert stored_portfolio is not None
    assert stored_portfolio.account_profile.account_id == acct_id

    stored_approval = lg_store.get_approval(lg_response.approval_artifact.approval_id)
    assert stored_approval is not None
    assert stored_approval.approval_status == "PENDING"
